version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: ../docker/backend.Dockerfile
    container_name: sentinel-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend/reports/output:/app/backend/reports/output
    env_file:
      - .env
    depends_on:
      - mongodb
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: ../docker/frontend.Dockerfile
    container_name: sentinel-frontend
    ports:
      - "3000:3000"
    env_file:
      - .env
    depends_on:
      - backend
    restart: unless-stopped

  mongodb:
    image: mongo:6.0
    container_name: sentinel-mongo
    ports:
      - "27017:27017"
    #volumes:
     # - mongo-data:/data/db
    volumes:
      - ./docker/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro

    restart: unless-stopped

volumes:
  mongo-data:

